### ISSUE TITLE
apktool is update to 2.7.0，Fixed a few bugs and is now available on Android 13

### ISSUE THREAD

**Issue by shuajinanhai** [kakathic/Tools#1]
please update apktool to 2.7.0 thank you very much

**Comment by kakathic** [comment]
> please update apktool to 2.7.0 thank you very much

Ok

**Comment by kakathic** [comment]
> please update apktool to 2.7.0 thank you very much

`Xu_install apktool 2.7.0`

You can use this command 

It will download directly from apktool homepage

**Comment by shuajinanhai** [comment]
i just want to use new aapt for android 13, hei hei

**Comment by kakathic** [comment]
> i just want to use new aapt for android 13, hei hei

https://github.com/rendiix/termux-aapt

i get aapt data here
